export * from './teacher.controller';
// export * from './auth.controller';
export * from './admin.controller';
export * from './intern.controller';
export * from './public.controller';
export * from './recommend-topic.controller';
export * from './report-intern.controller';
export * from './report-topic.controller';
export * from './result.controller';
// export * from './semester.controller';
export * from './student-intern.controller';
export * from './student-teacher.controller';
export * from './super-admin.controller';
export * from './super-teacher.controller';
export * from './teacher-group.controller';
